name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/*
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover -s tests

  merge-to-develop:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/*'
    steps:
      - name: Merge feature branch to develop
        run: |
          git fetch origin
          git checkout develop
          git merge --no-ff origin/${GITHUB_REF#refs/heads/}
          git push origin develop

  merge-to-main:
    needs: merge-to-develop
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Merge develop branch to main
        run: |
          git fetch origin
          git checkout main
          git merge --no-ff origin/develop
          git push origin main
